CREATE DATABASE FICBANK;
USE FICBANK;

CREATE TABLE CLIENTE(
	cl_id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL,
    telefone VARCHAR(14) NOT NULL,
    email VARCHAR(50) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    logradouro VARCHAR(50) NOT NULL,
    numero VARCHAR(6) NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
	ativo boolean,
	PRIMARY KEY (cl_id, cpf)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE CONTA(
	co_id INTEGER NOT NULL AUTO_INCREMENT,
	user VARCHAR(20) NOT NULL,
    senha VARCHAR(20) NOT NULL,
    saldo DOUBLE,
    cl_id INTEGER NOT NULL,
	ativo boolean,
	PRIMARY KEY (co_id, user)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE OP(
	op_id INTEGER NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(20) NOT NULL,
    PRIMARY KEY (op_id)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE TAG(
	ta_id INTEGER NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(20) NOT NULL,
	PRIMARY KEY (ta_id)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

