/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Model.Cliente;
import Model.Conta;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import views.panels.AdmCadCliente;
import views.panels.AdmCadConta;
import views.panels.AdmRequisicoes;

/**
 *
 * @author kassia
 */
public class AdmView extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
   AdmCadCliente admCadCliente;
   AdmCadConta admCadConta;
   AdmRequisicoes admRequisicoes;
    
    /**
     * Creates new form Dashboard
     */
    public AdmView() {
        
        initComponents();
        
        admCadCliente = new AdmCadCliente();
        admCadConta = new AdmCadConta();
        admRequisicoes = new AdmRequisicoes();
       
        MainPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        MainPanel.add(admCadCliente, c);
        
        c.gridx = 0;
        c.gridy = 0;
        MainPanel.add(admCadConta, c);
        
        c.gridx = 0;
        c.gridy = 0;
        MainPanel.add(admRequisicoes, c);
      
        admCadCliente.setVisible(true);
        admCadConta.setVisible(false);
        admRequisicoes.setVisible(false);
        
        this.revalidate();
        this.pack();
        this.repaint(); 
      
    
    }
    public AdmView(Conta conta, Cliente cliente) {
        initComponents();
        
    }

 //interação visual
   public void setColor(JPanel panel){
       panel.setBackground(new Color(73,83,122));
   }
   
   public void resetColor(JPanel panel){
       panel.setBackground(new Color(49,55,78));
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        pnl_clientes = new javax.swing.JPanel();
        lbl_pagamentos1 = new javax.swing.JLabel();
        pnl_contas = new javax.swing.JPanel();
        lbl_pagamentos = new javax.swing.JLabel();
        pnl_requisicoes = new javax.swing.JPanel();
        icon_extrato = new javax.swing.JLabel();
        lbl_extrato = new javax.swing.JLabel();
        pnl_resumo = new javax.swing.JPanel();
        icon_extrato1 = new javax.swing.JLabel();
        pnl_sair = new javax.swing.JPanel();
        lbl_pagamentos3 = new javax.swing.JLabel();
        pnl_dadosPessoais = new javax.swing.JPanel();
        Scrll_solicitacao = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");

        background1.setBackground(new java.awt.Color(255, 255, 255));

        pnl_header.setBackground(new java.awt.Color(255, 104, 104));

        logo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_LATERAL.png"))); // NOI18N
        logo1.setToolTipText("Ficbank");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Recursos Administrativos");

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(49, 55, 78));

        pnl_clientes.setBackground(new java.awt.Color(73, 83, 122));
        pnl_clientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_clientes.setPreferredSize(new java.awt.Dimension(161, 71));
        pnl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_clientesMouseClicked(evt);
            }
        });

        lbl_pagamentos1.setFont(lbl_pagamentos1.getFont().deriveFont(lbl_pagamentos1.getFont().getSize()+7f));
        lbl_pagamentos1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pagamentos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_pagamentos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/emoji_happy_circle [#537].png"))); // NOI18N
        lbl_pagamentos1.setText("CLIENTES");

        javax.swing.GroupLayout pnl_clientesLayout = new javax.swing.GroupLayout(pnl_clientes);
        pnl_clientes.setLayout(pnl_clientesLayout);
        pnl_clientesLayout.setHorizontalGroup(
            pnl_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clientesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_pagamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pnl_clientesLayout.setVerticalGroup(
            pnl_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_clientesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbl_pagamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_contas.setBackground(new java.awt.Color(49, 55, 78));
        pnl_contas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_contas.setPreferredSize(new java.awt.Dimension(161, 71));
        pnl_contas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_contasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_contasMouseEntered(evt);
            }
        });

        lbl_pagamentos.setFont(lbl_pagamentos.getFont().deriveFont(lbl_pagamentos.getFont().getSize()+7f));
        lbl_pagamentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pagamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_pagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/money [#1182].png"))); // NOI18N
        lbl_pagamentos.setText("CONTAS");

        javax.swing.GroupLayout pnl_contasLayout = new javax.swing.GroupLayout(pnl_contas);
        pnl_contas.setLayout(pnl_contasLayout);
        pnl_contasLayout.setHorizontalGroup(
            pnl_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_pagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnl_contasLayout.setVerticalGroup(
            pnl_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnl_requisicoes.setBackground(new java.awt.Color(49, 55, 78));
        pnl_requisicoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_requisicoes.setPreferredSize(new java.awt.Dimension(161, 71));
        pnl_requisicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_requisicoesMouseClicked(evt);
            }
        });

        icon_extrato.setToolTipText("Extrato");

        lbl_extrato.setBackground(new java.awt.Color(76, 81, 103));
        lbl_extrato.setFont(lbl_extrato.getFont().deriveFont(lbl_extrato.getFont().getSize()+7f));
        lbl_extrato.setForeground(new java.awt.Color(255, 255, 255));
        lbl_extrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_extrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/align_text_distribute [#914].png"))); // NOI18N
        lbl_extrato.setText("REQUISIÇÕES");

        javax.swing.GroupLayout pnl_requisicoesLayout = new javax.swing.GroupLayout(pnl_requisicoes);
        pnl_requisicoes.setLayout(pnl_requisicoesLayout);
        pnl_requisicoesLayout.setHorizontalGroup(
            pnl_requisicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_requisicoesLayout.createSequentialGroup()
                .addGroup(pnl_requisicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_requisicoesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(icon_extrato))
                    .addGroup(pnl_requisicoesLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_extrato, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnl_requisicoesLayout.setVerticalGroup(
            pnl_requisicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_requisicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_extrato, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(icon_extrato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_resumo.setBackground(new java.awt.Color(49, 55, 78));
        pnl_resumo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_resumo.setPreferredSize(new java.awt.Dimension(161, 71));

        icon_extrato1.setToolTipText("Extrato");

        pnl_sair.setBackground(new java.awt.Color(49, 55, 78));
        pnl_sair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_sair.setPreferredSize(new java.awt.Dimension(161, 71));
        pnl_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_sairMouseClicked(evt);
            }
        });

        lbl_pagamentos3.setFont(lbl_pagamentos3.getFont().deriveFont(lbl_pagamentos3.getFont().getSize()+7f));
        lbl_pagamentos3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pagamentos3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_pagamentos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door [#45].png"))); // NOI18N
        lbl_pagamentos3.setText("SAIR");

        javax.swing.GroupLayout pnl_sairLayout = new javax.swing.GroupLayout(pnl_sair);
        pnl_sair.setLayout(pnl_sairLayout);
        pnl_sairLayout.setHorizontalGroup(
            pnl_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sairLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_pagamentos3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnl_sairLayout.setVerticalGroup(
            pnl_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pagamentos3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_resumoLayout = new javax.swing.GroupLayout(pnl_resumo);
        pnl_resumo.setLayout(pnl_resumoLayout);
        pnl_resumoLayout.setHorizontalGroup(
            pnl_resumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_resumoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(icon_extrato1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        pnl_resumoLayout.setVerticalGroup(
            pnl_resumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_resumoLayout.createSequentialGroup()
                .addComponent(pnl_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(icon_extrato1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_dadosPessoais.setBackground(new java.awt.Color(49, 55, 78));
        pnl_dadosPessoais.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_dadosPessoais.setPreferredSize(new java.awt.Dimension(161, 71));

        javax.swing.GroupLayout pnl_dadosPessoaisLayout = new javax.swing.GroupLayout(pnl_dadosPessoais);
        pnl_dadosPessoais.setLayout(pnl_dadosPessoaisLayout);
        pnl_dadosPessoaisLayout.setHorizontalGroup(
            pnl_dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_dadosPessoaisLayout.setVerticalGroup(
            pnl_dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_resumo, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addComponent(pnl_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addComponent(pnl_contas, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addComponent(pnl_requisicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addComponent(pnl_dadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_contas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_requisicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_resumo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_dadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setMinimumSize(new java.awt.Dimension(834, 664));
        MainPanel.setPreferredSize(new java.awt.Dimension(834, 664));
        MainPanel.setLayout(new java.awt.BorderLayout());
        Scrll_solicitacao.setViewportView(MainPanel);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Scrll_solicitacao))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Scrll_solicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_contasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_contasMouseEntered
            // TODO add your handling code here:
    }//GEN-LAST:event_pnl_contasMouseEntered

    private void pnl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_clientesMouseClicked
        setColor(pnl_clientes);
        resetColor(pnl_contas);
        resetColor(pnl_requisicoes);
        resetColor(pnl_sair);
        
        admCadCliente.setVisible(true);
        admCadConta.setVisible(false);
        admRequisicoes.setVisible(false);
    }//GEN-LAST:event_pnl_clientesMouseClicked

    private void pnl_contasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_contasMouseClicked
        resetColor(pnl_clientes);
        setColor(pnl_contas);
        resetColor(pnl_requisicoes);
        resetColor(pnl_sair);
        
        admCadCliente.setVisible(false);
        admCadConta.setVisible(true);
        admRequisicoes.setVisible(false);
    }//GEN-LAST:event_pnl_contasMouseClicked

    private void pnl_requisicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_requisicoesMouseClicked
        resetColor(pnl_clientes);
        resetColor(pnl_contas);
        setColor(pnl_requisicoes);
        resetColor(pnl_sair);
        
        admCadCliente.setVisible(false);
        admCadConta.setVisible(false);
        admRequisicoes.setVisible(true);
    }//GEN-LAST:event_pnl_requisicoesMouseClicked

    private void pnl_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sairMouseClicked
        resetColor(pnl_clientes);
        resetColor(pnl_contas);
        resetColor(pnl_requisicoes);
        setColor(pnl_sair);
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane Scrll_solicitacao;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel icon_extrato;
    private javax.swing.JLabel icon_extrato1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_extrato;
    private javax.swing.JLabel lbl_pagamentos;
    private javax.swing.JLabel lbl_pagamentos1;
    private javax.swing.JLabel lbl_pagamentos3;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel pnl_clientes;
    private javax.swing.JPanel pnl_contas;
    private javax.swing.JPanel pnl_dadosPessoais;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_requisicoes;
    private javax.swing.JPanel pnl_resumo;
    private javax.swing.JPanel pnl_sair;
    // End of variables declaration//GEN-END:variables


}
